BookStore/urls.py
from django.contrib import admin
from django.urls import path, include
# from . import settings
from django.conf import settings

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('account/', include('account.urls')),
                  path('social-auth/',
                       include('social_django.urls', namespace='social')),
                  path('', include('catalog.urls')),
                  path('cart/', include('shoppingCart.urls')),
                  path('paypal/', include('paypal.standard.ipn.urls')),
                  path('orders/', include('orders.urls', namespace='orders')),
                  path('payment/', include('payment.urls', namespace='payment')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import path
from . import views

app_name = "catalogs"

urlpatterns = [
    path('', views.index, name='index'),
    path('item/<int:id>',
         views.book_detail,
         name='book_detail'),
    path('market/<str:market>',
         views.market_list,
         name='market'),
    path('contact',
         views.contact,
         name='contact'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

shoppingCart/urls.py
from django.urls import path
from . import views

app_name = "shoppingCars"

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add/<int:item_id>', views.add_item_to_cart, name="add_item"),
    path('remove/<int:item_id>', views.remove_item_in_cart, name="remove_item"),
]

shoppingCart/models.py
from django.db import models
from django.contrib.auth.models import User
from catalog.models import Book


class Cart(models.Model):
    belong_to = models.ForeignKey(
        to=User,
        related_name='production_list',
        on_delete=models.CASCADE
    )
    item = models.ForeignKey(
        to=Book,
        related_name='book',
        on_delete=models.CASCADE
    )
    number = models.PositiveSmallIntegerField(blank=False, default=1)
    created_time = models.DateTimeField(
        auto_now_add=True,
    )

    class Meta:
        ordering = ['belong_to']


    def get_belong_id(self):
        return self.belong_to.id

    def get_belong(self):
        return self.belong_to.username

    def get_cost(self):
        return self.item.price * self.number

shoppingCart/forms.py
from django import forms
from django.forms import widgets
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

from .models import Cart
from catalog.models import Book


class CartAddForm(forms.ModelForm):
    number = forms.IntegerField(min_value=0, required=False,
                                widget=widgets.NumberInput(attrs={
                                    'class': 'span1',
                                    'value size': '16',
                                    'style': 'max-width:34px',
                                }))
    class Meta:
        model = Cart
        fields = ('number',)

shoppingCart/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.decorators import login_required
from shoppingCart.models import Cart
from catalog.models import Book
from django.shortcuts import redirect
from .forms import CartAddForm
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.contrib.auth import authenticate


@login_required()
def cart(request):
    form = CartAddForm()

    items = Cart.objects.filter(belong_to=request.user)
    item_count = 0
    total = 0

    for item in items:
        if item.number > item.item.stock:
            item.number = item.item.stock
            item.save()
        item_count += item.number
        total = total + item.get_cost()

    context = {
        'form': form,
        'items': items,
        'item_count': item_count,
        'total': total}

    return render(request, 'shoppingcart/cart.html', context)


def add_item_to_cart(request, item_id):
    number = 1

    if request.method == "GET":
        if request.user.is_authenticated:
            item = Book.objects.filter(id=item_id).first()
            cart = Cart.objects.filter(belong_to=request.user, item=item).first()
            if item.stock < 1:
                return redirect('catalogs:index')
            if cart:
                cart.number = cart.number + number
                cart.save()
            else:
                Cart(belong_to=request.user, item=item, number=number).save()

            return redirect('catalogs:index')
        else:
            return redirect('accounts:customer_login')

    if request.method == "POST":
        form = CartAddForm(request.POST)

        if request.user.is_anonymous:
            return redirect('accounts:customer_login')

        if form.is_valid():
            item = get_object_or_404(Book, id=item_id)
            cart = get_object_or_404(Cart, belong_to=request.user, item=item)

            if form.cleaned_data['number'] is None:
                form.cleaned_data['number'] = 1

            if item.stock < form.cleaned_data['number']:
                error = "{} 庫存不足".format(item.title)
                return redirect('shoppingCars:cart')
            else:
                cart.number = form.cleaned_data['number']
                cart.save()
                return redirect('shoppingCars:cart')
        else:
            raise Http404


def remove_item_in_cart(request, item_id):
    if request.user.is_authenticated and request.method == "GET":
        cancel_target = Cart.objects.filter(belong_to=request.user, item=item_id)
        cancel_target.delete()
        return redirect('shoppingCars:cart')
    pass

shoppingCart/templates/shoppingcart/cart.html
{% extends "base.html" %}
{% block title %}Shopping list{% endblock %}
{% block content %}
    <div class="row">
    <div class="span12">
    <ul class="breadcrumb">
        <li><a href="{% url "catalogs:index" %}">首頁</a> <span class="divider">/</span></li>
        <li class="active">購物清單</li>
    </ul>
    <div class="well well-small">
    <h1>購物清單 <small class="pull-right"> {{ item_count }} 本書在購物車裡 </small></h1>
    <hr class="soften"/>

    <table class="table table-bordered table-condensed">
        <thead>
        <tr>
            <th>名稱名稱</th>
            <th>單價</th>
            <th>庫存</th>
            <th>數量</th>
            <th>小計</th>
            <th>取消購買</th>
        </tr>
        </thead>
        <tbody>

        {% for item in items %}
            <tr>
                <td><img width="100" src="{{ item.item.image.url }}" alt=""></td>
                <td>NT$ {{ item.item.price }}</td>
                {% if item.item.stock == 0 %}
                    <td>
                        <span class="label label-danger">缺貨中</span>
                    </td>
                    <td>
                        <span class="label label-danger">暫時不提供購買</span>
                    </td>
                    <td>
                        <span class="label label-danger">NT$ 0</span>
                    </td>
                {% else %}
                    <td>
                        {{ item.item.stock }}
                    </td>
                    <td>
                        <form method="post" action="{% url "shoppingCars:add_item" item.item_id %}">
                            {% csrf_token %}
                            <input type="number" name="number" class="span1" value size="16" style="max-width:34px"
                                   min="0" max="{{ item.item.stock }}" id="{{ form.number.auto_id }}"
                                   placeholder="{{ item.number }}">
                            <button class="btn btn-primary btn-small" type="submit">更新購物車</button>
                        </form>
                    </td>
                    <td>NT$ {% widthratio item.item.price 1 item.number %}</td>
                {% endif %}
                <td>
                    <a href="{% url "shoppingCars:remove_item" item.item_id %}" class="btn btn-mini btn-danger"><span
                            class="icon-remove"></span></a>
                </td>
            </tr>
        {% endfor %}
        <tr>
            <td colspan="4" class="alignR"><h2>總金額：</h2></td>
            <td class="label label-success"><h2>NT$ {{ total }}</h2></td>
        </tr>
        </tbody>
    </table>
    <br/>
    <a href="{% url "catalogs:index" %} " class="shopBtn btn-large">
        <span class="icon-arrow-left">
            繼續購物
        </span>
    </a>
    <a href="{% url "orders:order_create" %} " class="shopBtn btn-large pull-right">
        <span class="icon-arrow-right">
            結帳
        </span>
    </a>
{% endblock %}