BookStore/urls.py
from django.contrib import admin
from django.urls import path, include
# from . import settings
from django.conf import settings

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('account/', include('account.urls')),
                  path('social-auth/',
                       include('social_django.urls', namespace='social')),
                  path('', include('catalog.urls')),
                  path('cart/', include('shoppingCart.urls')),
                  path('paypal/', include('paypal.standard.ipn.urls')),
                  path('orders/', include('orders.urls', namespace='orders')),
                  path('payment/', include('payment.urls', namespace='payment')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
    path('customer-register/', views.customer_register, name='customer_register'),
    path('vendor-register/', views.vendor_register, name='vendor_register'),
    path(
        'login/', auth_views.LoginView.as_view(
            redirect_authenticated_user=True,
            template_name='account/login.html'
        ), name='customer_login'),
    path(
        'logout/', views.logout, name='logout'),
    path(
        'ChangePersonalInfo/', views.ChangePersonalInfo, name='change_personal_info'
    ),
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name='account/reset_password.html'),
         name='reset_password'),
    path('forget-password/', views.forget_password, name='forget_password')

]

catalog/urls.py
from django.urls import path
from . import views

app_name = "catalogs"

urlpatterns = [
    path('', views.index, name='index'),
    path('item/<int:id>',
         views.book_detail,
         name='book_detail'),
    path('market/<str:market>',
         views.market_list,
         name='market'),
    path('contact',
         views.contact,
         name='contact'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

shoppingCart/urls.py
from django.urls import path
from . import views

app_name = "shoppingCars"

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add/<int:item_id>', views.add_item_to_cart, name="add_item"),
    path('remove/<int:item_id>', views.remove_item_in_cart, name="remove_item"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap styles -->
    <link href="{% static "assets/css/bootstrap.css" %}" rel="stylesheet">
    <!-- Customize styles -->
    <link href="{% static "style.css" %}" rel="stylesheet">
    <!-- font awesome styles -->
    <link href="{% static "assets/font-awesome/css/font-awesome.css" %}" rel="stylesheet">


</head>
<body>
<!--
	Upper Header Section
-->
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="topNav">
        <div class="container">
            <div class="alignR">
                <div class="pull-left socialNw">
                    <a href="#"><span class="icon-twitter"></span></a>
                    <a href="#"><span class="icon-facebook"></span></a>
                    <a href="#"><span class="icon-youtube"></span></a>
                    <a href="#"><span class="icon-tumblr"></span></a>
                </div>
                <a href="{% url "catalogs:index" %}"> <span class="icon-home"></span> Home</a>
                <a href="#"><span class="icon-user"></span> My Account</a>
                {% if not request.user.is_authenticated %}
                    <a href="{% url "accounts:customer_register" %}"><span class="icon-edit"></span> Free Register </a>
                {% else %}
                    <a href="{% url "accounts:logout" %}"><span class="fa-sign-out-alt"></span> Logout </a>
                {% endif %}
                <a href="{% url "catalogs:contact" %}"><span class="icon-envelope"></span> Contact us</a>
                {% if not request.user.is_authenticated %}
                    <a href="{% url "accounts:customer_login" %}"><span class="icon-shopping-cart"></span>
                        0 Item(s)
                        - <span class="badge badge-warning"> NT$ 0 </span></a>
                {% else %}
                    <a href="{% url "shoppingCars:cart" %}"><span class="icon-shopping-cart"></span> {{ item_count }}
                        Item(s) - <span class="badge badge-warning"> NT$ {{ total }}</span></a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<!--
Lower Header Section
-->
<div class="container">
    <div id="gototop"></div>
    <header id="header">
        <div class="row">
            <div class="span4">
                <h1>
                    <a class="logo" href="{% url "catalogs:index" %}"><span>Twitter Bootstrap ecommerce template</span>
                        <img src="{% static 'assets/img/logo-bootstrap-shoping-cart.png' %}" alt="bootstrap sexy shop">
                    </a>
                </h1>
            </div>
        </div>
    </header>

    <!--
    Navigation Bar Section
    -->
    <div class="navbar">
        <div class="navbar-inner">
            <div class="container">
                <a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="nav-collapse">
                    <ul class="nav">
                        <li class="active"><a href="{% url "catalogs:index" %}">回到首頁</a></li>
                    </ul>
                    <ul class="nav pull-right">
                        <li class="dropdown">
                            {% if not user.is_authenticated %}
                                <a href="{% url "accounts:customer_login" %}"><span class="icon-lock"></span> Login </a>
                            {% else %}
                                <a href="#"><span class="icon-unlock"></span> Hi! {{ request.user.username }}</a>
                            {% endif %}
                        </li>
                    </ul>
                    <form action="#" class="navbar-search pull-right">
                        <input type="text" placeholder="Search" class="search-query span2">
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!--
    Body Section
    -->
    <!--
    Three column view
    -->

            {% block content %}{% endblock %}
    <!--
    Footer
    -->
    <footer class="footer">
        <div class="row-fluid">
            <div class="span2">
                <h5>Your Account</h5>
                <a href="#">YOUR ACCOUNT</a><br>
                <a href="#">PERSONAL INFORMATION</a><br>
                <a href="#">ADDRESSES</a><br>
                <a href="#">DISCOUNT</a><br>
                <a href="#">ORDER HISTORY</a><br>
            </div>
            <div class="span2">
                <h5>Iinformation</h5>
                <a href="contact.html">CONTACT</a><br>
                <a href="#">SITEMAP</a><br>
                <a href="#">LEGAL NOTICE</a><br>
                <a href="#">TERMS AND CONDITIONS</a><br>
                <a href="#">ABOUT US</a><br>
            </div>
            <div class="span2">
                <h5>Our Offer</h5>
                <a href="#">NEW PRODUCTS</a> <br>
                <a href="#">TOP SELLERS</a><br>
                <a href="#">SPECIALS</a><br>
                <a href="#">MANUFACTURERS</a><br>
                <a href="#">SUPPLIERS</a> <br/>
            </div>
            <div class="span6">
                <h5>The standard chunk of Lorem</h5>
                The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for
                those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et
                Malorum" by Cicero are also reproduced in their exact original form,
                accompanied by English versions from the 1914 translation by H. Rackham.
            </div>
        </div>
    </footer>
</div><!-- /container -->

<div class="copyright">
    <div class="container">
        <p class="pull-right">
            <a href="#"><img src="{% static "assets/img/maestro.png" %}" alt="payment"></a>
            <a href="#"><img src="{% static "assets/img/mc.png" %}" alt=" payment"></a>
            <a href="#"><img src="{% static "assets/img/pp.png" %}" alt="payment"></a>
            <a href="#"><img src="{% static "assets/img/visa.png" %}" alt="payment"></a>
            <a href="#"><img src="{% static "assets/img/disc.png" %}" alt="payment"></a>
        </p>
        <span>Copyright &copy; 2013<br> bootstrap ecommerce shopping template</span>
    </div>
</div>
<a href="#" class="gotop"><i class="icon-double-angle-up"></i></a>
<!-- Placed at the end of the document so the pages load faster -->
<link href="{% static "style.css" %}" rel="stylesheet">
<script src="{% static "assets/js/jquery.js" %}"></script>
<script src="{% static "assets/js/bootstrap.min.js" %}"></script>
<script src="{% static "assets/js/jquery.easing-1.3.min.js" %}"></script>
<script src="{% static "assets/js/jquery.scrollTo-1.4.3.1-min.js" %}"></script>
<script src="{% static "assets/js/shop.js" %}"></script>
</body>
</html>